# Generated by Django 6.0.3 on 2026-03-23 14:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Используйте визуальный редактор для текста, изображений и встраиваемого медиа.', verbose_name='Текст объявления'),
        ),
    ]
